### ISSUE TITLE
[BUG] `vahadane` and `augment` normalizer might not always work 

### ISSUE THREAD

**Issue by matte-esse** [jamesdolezal/slideflow#212]
## Description
Setting `"normalizer"` to `"reinhard"` or `"augment"` might generate the following error. It is yet to be defined what other parameters/libraries versions/conditions have to be there for the error to occur. 

[error.log](https://github.com/jamesdolezal/slideflow/files/10375851/error.log)

## To Reproduce / Environment
As stated it is not yet clear when the error occurs. Nonetheless, a list of the libraries versions of the environment in which the error occurred are attached below

[errorPIPfreeze.txt](https://github.com/jamesdolezal/slideflow/files/10375874/errorPIPfreeze.txt)

Python==3.9.15

**Comment by jamesdolezal** [comment]
Thanks Matt. I was able to reproduce the error with the following:

```python
import slideflow as sf
P = sf.Project('.../slideflow_test/project')
hp = sf.ModelParams(tile_px=71, tile_um=1208, normalizer='augment', include_top=False)
P.train('category1', params=hp)
```

The error is raised because the Tensorflow autograd can't detect the Tensor shapes from the Augment & Vahadane normalizers. The fix, included in 604208a, adds an explicit `.set_shape()` call.

As a side note, I would not recommend doing real-time normalization with the Vahadane normalizer. [Our benchmarks](https://slideflow.dev/norm.html) show that Vahadane throughput is only 1 image per second, which is far too slow for use in real-time during training. Instead, if you plan to use vahadane normalization, I would recommend doing the normalization at the time of tile extraction (`P.extract_tiles(..., normalizer='vahadane')`)
