### ISSUE TITLE
Attention heatmaps look "cold" all over

### ISSUE THREAD

**Issue by sreens** [jamesdolezal/slideflow#233]
Hello,

 This is more of an understanding issue than a bug/error that I am facing. I have trained a model that has decent predictive performance, yet the attention heatmaps it produces for samples that it correctly predicts to be of the target class are cold all over i.e. the attention scores are almost always negative and extremely small number of tiles have positive attention. I am confused as to how this can be reconciled with the fact that the prediction performance is good. Any thoughts or ideas would be appreciated.

Best,
Sameet

**Comment by jamesdolezal** [comment]
Hi Sameet!

This behavior does seem consistent with the results I get using CLAM, as well. I think this is due to the attention gating mechanism, which is optimized in such a way that only a few tiles from a slide may pass the attention gating and be used to generate the prediction. It does present difficulties for heatmap visualization, as you mention, as the entire heatmap often appears "cold".

We are in the final stages of assembling a manuscript for Slideflow, and in this paper we compare heatmaps generated using traditional tile-based models and attention-based heatmaps using MIL.  Most of the MIL heatmaps appear globally "colder" than the tile-based model heatmaps, although the important areas are often represented in both. As an example, this is a heatmap from a traditional tile-based model:

![TCGA-BA-A6DA-01Z-00-DX1 8BFA179A-8E8A-45DC-A036-77A7D6ABB7EA_HPV_neg](https://user-images.githubusercontent.com/48372806/227262777-60203654-15bc-4047-9689-410508353018.png)

And this is a heatmap from an MIL model trained to the same outcome:

![TCGA-BA-A6DA-01Z-00-DX1 8BFA179A-8E8A-45DC-A036-77A7D6ABB7EA_attn](https://user-images.githubusercontent.com/48372806/227262885-c53b8a81-f18f-4caf-af8a-4c5c009b8bdb.png)

There is a similar overall pattern in both (which supports that the MIL heatmaps are likely displayed correctly), but the attention heatmap is lower resolution and generally "colder".

It's an interesting observation that we haven't totally figured out how to solve. We may try gating out the low-attention areas when calculating the colormap scale, which could help improve global "brightness" of the heatmaps. 

We're currently working on a global revamp of the MIL submodule for version 1.6 (which will include a new MIL architecture). If you have any thoughts or ideas on attention heatmap visualization, I would be happy to experiment and include it in a future release!

**Comment by jamesdolezal** [comment]
I'm going to go ahead and close this issue - reply here if the issue persists or if you would like to continue the discussion, and I will reopen.

**Comment by sreens** [comment]
Thank you for your very helpful response James, and apologies for my delay in responding to you. It is fine to close the issue for now. I might seek permission later to briefly cite our exchange (or your preprint if it is out by then) if my team and I decide to put our findings into a manuscript. Best, Sameet
