### ISSUE TITLE
slidemap save() and save_umap() encountered zip file problems in Databricks

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#268]
## Description

Hi James, I mentioned this in Databricks compatibility request but just to better track this issue. I encountered zip file issue again when running slide_map.save_umap('path') even after I defined the environment variable. I believe SlideMap.save() has the same issue.

## To Reproduce
1. slidemap=features.map_activations()
2. slidemap.save_umap('path')
3. slidemap.ave('path')

<img width="508" alt="error" src="https://user-images.githubusercontent.com/13988409/235701184-19949bb4-cae6-47ce-a5f7-0583b9691c0d.png">

## Environment:

 - Slideflow Version (e.g., 1.0): 2.0.3
 - OS (e.g., Ubuntu): Ubuntu in Databricks
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.10
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Meijian** [comment]
Perfect! Thank you James.

**Comment by jamesdolezal** [comment]
Unfortunately, this isn't something that can be easily patched. The culprit issue is the `np.savez()` functions in `SlideMap.save_umap()` and `SlideMap.save_encoder`. In both cases, `np.savez()` is used to save the UMAP range and clipping information (values used for normalizing the UMAP-transformed data into the range 0-1). This information is saved to an `npz` file, storing the range information under the key `range` and the clipping information under the key `clip`. 

The range and clipping information is necessary when load a saved UMAP object from file, otherwise the UMAP object will no longer be able to transform data in the same way. 

The `npz` file format uses zipping under the hood, which is why it's incompatible with databricks.

For the index files, I was able to switch from `npz` files to `npy` files, which don't use zipping. Unfortunately, `npy` files can only store a single array - and in this case we need to store two: the range information and clip information. So you won't be able to save fully save the UMAP encoder on a file system that doesn't have zip support.

You can, however, still save an *image* of the UMAP and the coordinates for all shown tiles. Instead of using `SlideMap.save()`, use `SlideMap.save_plot()` to save only an image of the UMAP. Use `SlideMap.save_coordinates()` to save the coordinates for tiles shown on the plot.

I hope that's helpful, and sorry we can't make that functionality fully compatible with the databricks system.

**Comment by Meijian** [comment]
Hi James, it's okay. I was able to output UMAP coordinates and plots. So it's not a big deal. Thanks for looking into it.
