### ISSUE TITLE
Balancing Unbalanced Categorical Datasets with Image Augmentation

### ISSUE THREAD

**Issue by millea46** [jamesdolezal/slideflow#320]
## Feature

It would be nice to see a clear and concise example of how you would go about balancing categorical data in the Slideflow pipeline using the built in image augmentation.

## Pitch

We are using the Slideflow pipeline as a tool for categorical classification. It has, thus far, been very intuitive and useful. However, we have an unbalanced dataset for which we are trying to build a classification model.  We were hoping to use image augmentation to improve the balance of the training data, but it is difficult to implement in the workflow without clear examples. It would be nice to see an example of image augmentation written out in the format of the other great examples provided in the Slideflow documentation.

## Alternatives

We have of course attempted to balance the dataset using the balance method built into Slideflow Datasets. The mini-batch categorical balancing that is performed by the balance method ended up not working for our dataset, so we are looking for additional options.

## Additional context

We have read the documentation of slideflow.io.torch/tensorflow interleaving and augmentation, and without clear examples, it is difficult to determine how the prefetch datasets generated by these methods fit into the pipeline. Any examples would be of great help. Thanks

**Comment by jamesdolezal** [comment]
Hi millea46 - this is a great suggestion. 

We'll work on putting together some clearer examples of how to work with the IO pipeline for augmenting datasets. I'll circle back here once we have some better examples, and we can discuss if any further clarifications or new features would be helpful for your application.

**Comment by millea46** [comment]
Thank you for the quick response. We will look forward to your updates!

**Comment by jamesdolezal** [comment]
Sorry this took so long to put together! We've put together a detailed guide to dataloaders, oversampling, undersampling, and augmentations in a new "Developer Notes" section of the documentation. You can find the working draft of this section here: https://github.com/jamesdolezal/slideflow/blob/dev/docs-source/source/dataloaders.rst

These the "Developer Notes" will be included in the documentation at https://slideflow.dev once version 2.2 is released. We anticipate release in 1-2 weeks. 

In the meantime, I'd greatly appreciate any feedback you have on this section. Does it help answer your questions about sampling and augmentations? Are there any further detailed you think would be helpful?

Thanks again for the suggestion!

**Comment by jamesdolezal** [comment]
Version 2.2 is released, and with it we've greatly expanded our documentation to provide better insights into  oversampling and undersampling options.

Per your request, we've added a new tutorial that walks you through the process of oversampling a dataset with custom augmentations (see: `[Tutorial 7](https://slideflow.dev/tutorial7/)`)

If you're looking for deeper insights into how our oversampling and undersampling methods work under the hood, we have a new developer notes section that addresses this topic (see [here](https://slideflow.dev/dataloaders/)).

I hope that answers your question! Let me know if you have any feedback, thoughts, or questions.

**Comment by millea46** [comment]
Thank you for providing great feedback in such a timely manner. The new features in version 2.2 look great. Having read through the new documentation on augmentation and balancing, I am still not sure if I quite understand how to do what I need within the Slideflow framework. 

> We are interested in oversampling an unbalanced class by randomly augmenting tiles in the smaller class to create new records. For example, if Group 1 has 10 records and Group 2 has 5 records, we would generate 5 new records for Group 2 by oversampling from Group 2. Within each of the individual oversampled records, tiles would be randomly augmented (flipped, rotated, blurred, etc.) to create "unique" records. So essentially, we want to generate 5 more augmented data records by randomly selecting from different augmentation method (such as rotation and flipping) on the fly and then combining it with the original 5 records to create the balanced data during the training.

Apologies if this process is laid out in the documentation. We appreciate all the effort you put into adding this improvement and look forward to future update. Thanks again.

**Comment by jamesdolezal** [comment]
This is essentially what the existing oversampling method does; it's mostly a matter of perspective. Below is a figure that illustrates our oversampling approach, using the example you've raised: Group 1 with 10 total records (tiles) and Group 2 with 5 total records (tiles). 

![Oversampling](https://github.com/jamesdolezal/slideflow/assets/48372806/8296eba6-8d8d-418f-bb7d-6d6580432cc0)

With standard, tile-based balancing (essentially no oversampling), every tile has equal probability of being selected. You'll get more representation from Group 1 than Group 2 in an epoch, since there are more tiles in Group 1.

With category-level balancing, tiles are sampled with greater probability from Group 2 than Group 1, resulting in an even distribution of tiles across categories. Because an epoch is defined as the number of tiles that would equal a full pass through the dataset (15 tiles, in this case), this higher probability of taking from of Group 2 means that some tiles will be repeated, or oversampled. 

All images undergo augmentation, so this is oversampling approach is effectively the same thing as generating augmented records before training, except it's done on-the-fly while sampling from the dataset. The only difference is that if you were to generate augmented records before training (e.g. increasing the dataset size to a total of 20 records), the epoch size would increase from 15 to 20. Whereas with this approach, an epoch is still defined as 15 tiles. If you want to simulate the larger epoch size of having oversampled, augmented data in the least frequent class, you can manually override the epoch size using the `steps_per_epoch_override` argument to [Project.train()](https://slideflow.dev/project/#slideflow.Project.train). But that should make a practical difference.
