### ISSUE TITLE
Latest foundation models?

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#392]
## Feature
I'm wondering if the latest pathology foundation models, such as UNI, GigaPath, and Virchow, will be implemented as feature extractors in Slideflow soon.

I haven't tried the Custom Feature Extractor tutorial from this page: https://slideflow.dev/custom_extractors/. Is this the framework we should use to implement these foundation models? If not, will Slideflow provide a framework for us to do so?

Thanks!

**Comment by jamesdolezal** [comment]
Very timely suggestion - UNI and Virchow are both already implemented and available on the `dev` branch. Because of access restrictions, you'll need to request access to both models on Hugging Face and download the model weights (`pytorch_model.bin`). These feature extractors accept the pretrained weights as an additional argument:

```python
import slideflow as sf

virchow = sf.build_feature_extractor("virchow", weights=".../pytorch_model.bin")
```

Both of these will be included in the 2.4.0 release, which is imminent. We haven't yet integrated GigaPath but it's on our list. If there are any others you would like supported, please add them to this issue list and we will prioritize.

**Comment by Meijian** [comment]
That's awesome! I look forward to trying them out. These are the latest ones that I can think of, I will put in requests if I see other models that we want to try!

**Comment by Meijian** [comment]
Close this as the release is underway!

**Comment by Meijian** [comment]
Close this as the release is underway.

**Comment by jamesdolezal** [comment]
Just to comment, we have now also integrated Gigapath. All these new feature extractors will be included in our next release, which is coming soon. This means Slideflow will soon have:

- CTransPath
- RetCCL
- UNI (Harvard)
- HistoSSL (Owkin)
- Virchow (PaigeAI)
- Gigapath (Microsoft)
- PLIP (Stanford)

The upcoming release is going to include a more permissive license that explicitly allows commercial use, and the work required to make this possible has resulted in some delays in our original release time frame. Much of the work is now complete, so I'm hoping we can release it soon.
